<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TwoExcelSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>24ef5cf4-e1b3-4f48-9c48-479c9e828873</testSuiteGuid>
   <testCaseLink>
      <guid>d7857b0b-b404-4509-9455-1a5c1f723c03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDriven/TwoExcelDD</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>eef107b9-4c93-48f1-91d0-abda7450770e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataDrivenTwoExcel/TwoExcel_01</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e8ba8f22-b43a-4a20-a744-cee957047783</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataDrivenTwoExcel/TwoExcel_02</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>e8ba8f22-b43a-4a20-a744-cee957047783</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>60e8f991-6d9b-4d02-a73f-e2b599faf2e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e8ba8f22-b43a-4a20-a744-cee957047783</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>804add0e-a94e-4c4f-8dbb-d5abbcfad21a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eef107b9-4c93-48f1-91d0-abda7450770e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>facility</value>
         <variableId>9c896300-c377-4529-9940-503d9bc291af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>eef107b9-4c93-48f1-91d0-abda7450770e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comments</value>
         <variableId>452b60d5-2f4c-4bae-b30f-20d46fdcf6f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
